# SPDX-License-Identifier: BSD-3-Clause
# Copyright (c) 2020-2022 Intel Corporation

---
# This role check the updated kernel after installation
- name: Get updated facts
  setup:
  tags:
     - check_updated_kernel

- name: Kernel Version OK Check
  debug:
    msg: Kernel Version is OK {{ ansible_kernel }}
  when: ansible_kernel is version (installed_kernel, '>=')
  tags:
     - check_updated_kernel

- name: Kernel Version Not OK Check
  fail:
    msg: Kernel Version is Not OK {{ ansible_kernel }}
  when: ansible_kernel is version (installed_kernel, '<')
  tags:
     - check_updated_kernel

- name: check i40e_xsk_wakeup
  shell: nm /lib/modules/$(uname -r)/kernel/drivers/net/ethernet/intel/i40e/i40e.ko | grep -q i40e_xsk_wakeup && echo "FOUND" || echo "NOT FOUND"
  register: i40e_check_output
  tags:
    - check_updated_kernel

- name: Print i40e_xsk_wakeup result
  debug: #TODO Change to fail
    msg: i40e_xsk_wakeup check result {{ i40e_check_output.stdout }}
  when: i40e_check_output.stdout != "FOUND"
  tags:
     - check_updated_kernel

- name: Checks summary
  debug:
    msg:
      - Kernel Version {{ ansible_kernel }} required is {{ installed_kernel }}
      - i40e_xsk_wakeup check result {{ i40e_check_output.stdout }}
  tags:
    - check_updated_kernel
