# SPDX-License-Identifier: BSD-3-Clause
# Copyright (c) 2020-2025 Intel Corporation.

[package]
name = "cndp-cne-sys"
description = "Cloud Native Data Plane (CNDP) Rust Bindings"
repository = "https://github.com/CloudNativeDataPlane/cndp"
homepage = "https://cndp.io/"
readme = "README.md"
version = "0.2.0"
edition = "2021"
license = "BSD-3-Clause"
keywords = ["networking", "cloud native", "AF_XDP"]
rust-version = "1.63"

[lib]
name = "cne_sys"

[build-dependencies]
bindgen = "^0.59"
cc = "^1.0.0"
pkg-config = "^0.3"
os_info = "^3.5.0"
shellexpand = "^2.1"
