name: cppcheck-action-test
on: [push] # yamllint disable-line rule:truthy

jobs:
  build:
    name: cppcheck-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: cppcheck
        uses: deep5050/cppcheck-action@main
        with:
          github_token: ${{ secrets.GITHUB_TOKEN}}

      - name: cat report
        run: |
            cat cppcheck_report.txt
